# Generated by Django 5.1.6 on 2025-02-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicesAccounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('accounted', 'Accounted'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
    ]
