# Generated by Django 5.1.6 on 2025-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicesAccounting', '0002_alter_invoicemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
