# Generated by Django 5.1.6 on 2025-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicesAccounting', '0002_invoice_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('accounted', 'Accounted'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
