# Generated by Django 5.1.6 on 2025-02-12 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicesAccounting', '0004_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
